# Generated by Django 4.2.15 on 2024-08-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name_plural': 'vendor'},
        ),
    ]
