# Generated by Django 4.2.15 on 2024-08-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_product_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='vid',
            new_name='pid',
        ),
    ]
